apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-1
  namespace: cd
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/wangwei1981/docker-development-youtube-series
